import Modal from "@/components/Modal";
import ChartModal from "@/components/ChartModal";
import "./globals.css";

export const metadata = {
  title: "DASHBOARD | DC AMBAL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#F5F6F8]">
        {children}
        <Modal />
        <ChartModal />
      </body>
    </html>
  );
}
